### ISSUE TITLE
Rounding to another decimal place

### ISSUE THREAD

**Issue by onetrev** [yasinkuyu/brackets-units#2]
I noticed that EM's (and looks like the upcoming but not yet published on Brackets version which supports REMs) round to only two decimal places?

As such, we aren't getting perfect PX to EM / REM calculations. 19 PX is convered to 1.19em, where it should be 1.188em. 

Testing it out, looks like all that is needed is changing the decimals value to 3 on line 188 of InlineUnitHelper.js.

**Comment by onetrev** [comment]
@yasinkuyu Sorry to ping you again on this, just wondering if you are going to push v0.0.7 to the Brackets Extension repository?

**Comment by yasinkuyu** [comment]
Hi, I'm working on a new version over .

**Comment by onetrev** [comment]
Excellent, this is good to hear. Hopefully you saw the original issue for this item before you closed it, changing the decimals value to **3** on line 188 of InlineUnitHelper.js so that the proper conversions occur. Thanks again!!
